FROM maven:3.6.3-openjdk-15 AS build
COPY ./ /app
WORKDIR /app
RUN mvn --show-version --update-snapshots --batch-mode clean package

FROM adoptopenjdk:12-jre-hotspot
RUN mkdir /app
WORKDIR /app
COPY --from=build ./app/api/target/suggestions-api-1.0-SNAPSHOT.jar /app
EXPOSE 8081
CMD ["java", "-jar", "suggestions-api-1.0-SNAPSHOT.jar"]
