apiVersion: apps/v1
kind: Deployment
metadata:
  name: suggestions-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suggestions
  template:
    metadata:
      labels:
        app: suggestions
    spec:
      containers:
        - image: kolan51/rso2021-suggestions:2021-12-31-21-01-57
          name: suggestions
          env:
            - name: REST-PROPERTIES_CUSTOMERSURL
              value: http://20.120.64.197/customers/v1/customers
            - name: KUMULUZEE_CONFIG_CONSUL_AGENT
              value: http://52.150.43.117:8500/
            - name: KUMULUZEE_DISCOVERY_CONSUL_AGENT
              value: http://52.150.43.117:8500/
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: suggestions
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: suggestions