kumuluzee:
  name: suggestions-service
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  config:
    consul:
      agent: http://localhost:8500
  health:
    checks:
      disk-space-health-check:
        threshold: 100000000
      http-health-check:
        connection-url: https://atlas.microsoft.com/weather/forecast/daily/json?api-version=1.0
    metrics:
      web-instrumentation:
        - name: suggestions-endpoint
          url-pattern: /v1/suggestions/*
      servlet:
        enabled: true
        mapping: /metrics
      logs:
        enabled: true
        type: readiness
        level: FINE
        period-s: 60
  fault-tolerance:
    annotation-overrides:
      - class: si.fri.rso2021.Payments.api.v1.resources.SuggestionsResources
        method: makeObjectRequest
        annotation: retry
        parameters:
          max-retries: 15
  streaming:
    kafka:
      producer:
        bootstrap-servers: glider-03.srvs.cloudkafka.com:9094
        acks: all
        retries: 0
        batch-size: 16384
        linger-ms: 1
        buffer-memory: 33554432
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        security-protocol: SASL_SSL
        sasl-mechanism: SCRAM-SHA-256
        group-id: newer
        enable-auto-commit: true
        auto-commit-interval-ms: 1000
        auto-offset-reset: earliest
        session-timeout-ms: 30000
        sasl-jaas-config:
          username: xb9xnuao
          password: Xp09QfLtNN2nvExTgf1IxKKJoKJ5qiaE
rest-properties:
  maintenance-mode: false
  broken: false
  customersurl: http://localhost:8080/v1/customers


# docker run -d --name rso-workerdb -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=workers -p 5432:5432 postgres:13
# kumuluzee.env.name če bi bilo znotraj
# če datoteka: velike črke in podčrtaj namesto pik KUMULUZEE_ENV_NAME

# docker network create rso2021
# docker run -d --name rso-workerdb -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=workers -p 5432:5432 --network rso2021 postgres:13
# docker -p HOST:CONTAINER

# okoljske spremenljivke: v run ukazu z -e IME=vrednost
# jdbc:postgresql://worker-database:5432/workers
# KUMULUZEE_DATASOURCES0_CONNECTIONURL -> sestavljeno iz nivojev te yaml datoteke, 0 tam kjer lahko več
# docker run -d --name workers-MS -p 8080:8080 -e KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://rso-workerdb:5432/workers --network rso2021 rso2021.v1

# consul agent -dev, na 8500 portu