kumuluzee:
  name: suggestions-service
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  config:
    consul:
      agent: http://52.150.43.117:8500
  health:
    metrics:
      web-instrumentation:
        - name: suggestions-endpoint
          url-pattern: /v1/suggestions/*
      servlet:
        enabled: true
        mapping: /metrics
  fault-tolerance:
    annotation-overrides:
      - class: si.fri.rso2021.Payments.api.v1.resources.SuggestionsResources
        method: makeObjectRequest
        annotation: retry
        parameters:
          max-retries: 15
rest-properties:
  maintenance-mode: false
  broken: false
  customersurl: http://20.120.64.197/customers/v1/customers
  apikey: Aq5NNU-8Bhp2XOoXGtR4lX8sNGiXGKcrD4jnK2UqPD


# docker run -d --name rso-workerdb -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=workers -p 5432:5432 postgres:13
# kumuluzee.env.name če bi bilo znotraj
# če datoteka: velike črke in podčrtaj namesto pik KUMULUZEE_ENV_NAME

# docker network create rso2021
# docker run -d --name rso-workerdb -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=workers -p 5432:5432 --network rso2021 postgres:13
# docker -p HOST:CONTAINER

# okoljske spremenljivke: v run ukazu z -e IME=vrednost
# jdbc:postgresql://worker-database:5432/workers
# KUMULUZEE_DATASOURCES0_CONNECTIONURL -> sestavljeno iz nivojev te yaml datoteke, 0 tam kjer lahko več
# docker run -d --name workers-MS -p 8080:8080 -e KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://rso-workerdb:5432/workers --network rso2021 rso2021.v1

# consul agent -dev, na 8500 portu